### PR TITLE
Fix make test #9

### PR DESCRIPTION
**Pull request by vorburger**
Hello @elenawinters, I stumbled upon `kingraph` from @rstacruz and noticed (just by looking at https://github.com/rstacruz/kingraph/network) that your fork, via @constantinmaes @AlexanderWillner @vabene1111) appears to be the most recently actively maintained repository.

Are you, are any of the other intermediate repo owners, interested in pull requests for it?

For example, I noticed that `make test` doesn't appear to work as-is.

This PR fixes one of the problems I ran into (and there are others).

Just thought I would reach out, but feel free to ignore!

### CODE REVIEW

**Comment by vorburger** [comment]
PS: If `make test` actually fully passes (green) for you, then the discrepancy may be due to differing versions of `graphviz` we're using? In that case, the simplest is probably to standardize the version for the build with a (docker)  container.

**Comment by elenawinters** [comment]
I haven't been working on this recently. Not a fan of the old code and was gonna write my own piece of software that accomplishes my goals at some point.

I'll review the PR when I'm able to. Just remember that the colors used in produced images of this fork are different from the other repositories.

**Comment by vorburger** [comment]
Thanks for super quick feedback! Sure thing. Shout when you write your own thing... 😄 

I just noticed that this contains 2 commits by mistake; I meant to only change the image to fix the test, so I'll rm the other commit.

For anyone else ever reading this, I might continue toying with this project over in my fork.

**Comment by AlexanderWillner** [comment]
@vorburger thanks! Seems Test 9 differs here. Looks like the font is rendered slightly different...

**Comment by vorburger** [comment]
> @vorburger thanks! Seems Test 9 differs here. Looks like the font is rendered slightly different...

Oh, really? I didn't even notice any font difference 😸 yet... The problem was also "dark theme" (a cool change that I personally do like which was introduced by @elenawinters, just the tests were not yet updated apparently) as well as some discrepancy between code/examples/test re. `gender` vs `sex`, which I just [fixed here](https://github.com/vorburger/kingraph/commit/adaa9b3baf8238efff5c5eb7a6d62ad7d76cd851)).

@AlexanderWillner do you have any interest in actively maintaining Kingraph? 😈

**Comment by elenawinters** [comment]
Font difference may be noticeable because the font color was changed in my color scheme.

**Comment by elenawinters** [comment]
Or, not noticeable in my scheme. Words are hard

**Comment by elenawinters** [comment]
With all this talk about kingraph I might start to make more contributions, although I don't think that using this fork would be wise for further development.

This fork was really just for me to turn the theme to a dark one, so I could actually work on trees and what not without searing my eyeballs off.

One of the things that, if I don't get around to it, would recommend being added to kingraph, would be the ability to configure the theme from each individual yaml graph setup file.

**Comment by AlexanderWillner** [comment]
> @AlexanderWillner do you have any interest in actively maintaining Kingraph? 😈

Not really ;) But might help getting the code a bit cleaner. Might make sense to have a GitHub Kingraph Organization - but at the end, doesn't matter which repo to improve step by step.

**Comment by rstacruz** [comment]
Thank you all for continuing the work on kingraph! ~~If anyone wants the kingraph name on npm, would love to hear from the community which fork should go there.~~ (edit: my bad, i never had the name to begin with 😅 , but happy to make an edit on the readme for my repo to point to the most active fork)

**Pull request merged**
